apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: microservices
resources:
  - namespace.yaml
  - configmap.yaml
  - secret.example.yaml
  - postgres.yaml
  - zookeeper.yaml
  - kafka.yaml
  - services.yaml
  - network-policy.yaml
